builds:
  -
    binary: whaturl


brews:
  -
    name: whaturl
    description: "A CLI for creating titled markup language links out of text containing raw URLs"
    homepage: "https://github.com/staticaland/go-whaturl"

    goarm: 6

    goamd64: v3

    tap:
      owner: staticaland
      name: go-whaturl

    folder: Formula

    install: |
      bin.install "whaturl"
