builds:
  -
    binary: whaturl


brews:
  -
    name: whaturl
    description: "A CLI for creating titled markup language links out of text containing raw URLs"
    homepage: "https://github.com/staticaland/go-whaturl"

    goarm: 6

    goamd64: v3

    tap:
      owner: staticaland
      name: go-whaturl

    folder: Formula

    install: |
      bin.install "whaturl"

changelog:
  sort: asc

  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - OK
      - Merge pull request
      - Merge branch
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - 'Brew formula update'
