# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whaturl < Formula
  desc "A CLI for creating titled markup language links out of text containing raw URLs"
  homepage "https://github.com/staticaland/go-whaturl"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/staticaland/go-whaturl/releases/download/v0.2.0/go-whaturl_0.2.0_darwin_arm64.tar.gz"
      sha256 "23076f0d9985626657d125f124622b15c2ad3756644dbce5a30981b5c0fe79b2"

      def install
        bin.install "whaturl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/staticaland/go-whaturl/releases/download/v0.2.0/go-whaturl_0.2.0_linux_arm64.tar.gz"
      sha256 "aad88a0668a3aa9820302a8f1b6d7c9513831115e0782f72239786ad380af661"

      def install
        bin.install "whaturl"
      end
    end
  end
end
