baseURL = 'https://staticaland.github.io/go-whaturl/'
languageCode = 'en-us'
title = 'go-whaturl'

theme = "hugo-book"


[params]

  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'
