name: GoReleaser
"on":
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: 1.18.5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify:
    name: Perform Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Ring the bell
        uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302
        with:
          channel-id: workflows
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"A new version of `whaturl` has been released: `yo` :tada:"},"accessory":{"type":"button","text":{"type":"plain_text","text":"See details"},"url":"https://github.com/staticaland/go-whaturl/releases"}}]}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
permissions:
  contents: write
