name: GoReleaser
"on":
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v3
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify:
    name: Perform Slack notification
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: workflows
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"A new version of `whaturl` has been released: `yo` :tada:"},"accessory":{"type":"button","text":{"type":"plain_text","text":"See details"},"url":"https://github.com/staticaland/go-whaturl/releases"}}]}'
