name: Vale
"on":
  pull_request:
    paths:
      - '**.org'
      - '**.md'
  push:
    paths:
      - '**.org'
      - '**.md'
jobs:
  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - channel-id: workflows
        uses: slackapi/slack-github-action@v1.21.0
        with:
          payload: '{"text":"Deployment started (In Progress)","attachments":[{"pretext":"Deployment started","color":"dbab09","fields":[{"title":"Status","short":true,"value":"In Progress"}]}]}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail_on_error: true
          reporter: github-check
      - channel-id: workflows
        uses: slackapi/slack-github-action@v1.21.0
        with:
          payload: '{"text":"Deployment finished (Completed)","attachments":[{"pretext":"Deployment finished","color":"28a745","fields":[{"title":"Status","short":true,"value":"Completed"}]}]}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
